/**
 * Data Explorer Service
 * API Service that reads from Elasticsearch.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import FieldsResponse from '../model/FieldsResponse';

/**
* Fields service.
* @module api/FieldsApi
* @version 0.0.1
*/
export default class FieldsApi {

    /**
    * Constructs a new FieldsApi. 
    * @alias module:api/FieldsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the fieldsGet operation.
     * @callback module:api/FieldsApi~fieldsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/FieldsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns dataset fields for field search.
     * @param {module:api/FieldsApi~fieldsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/FieldsResponse}
     */
    fieldsGet(callback) {
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = FieldsResponse;

      return this.apiClient.callApi(
        '/fields', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }


}
