version: '3'
services:
  nginx_proxy:
    # Child services must have links named "ui", "api".
    image: nginx
    ports:
      - 4400:4400
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - ui
      - api
  ui:
    build:
      context: ui
    volumes:
      - ./ui:/ui
      # See https://stackoverflow.com/a/32785014 for why this is needed.
      - /ui/node_modules
  api:
    # Build Dockerfile from repo root - not api/ - since config/ is in repo root
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - 8390:8390
    volumes:
      # Mount the python source so that code changes don't require rebuilding
      # the image. Changes to requirements.txt will still require rebuilds.
      - ./api/data_explorer:/app/data_explorer
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    ports:
      - 5601:5601
  # For convenience, load test data into Elasticsearch.
  index_test_data:
    build:
      context: test
