version: '3'
services:
  nginx_proxy:
    # Child services must have links named "ui", "api".
    image: nginx
    ports:
      - 4400:4400
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - ui
      - api
  ui:
    build:
      context: ui
    volumes:
      - ./ui:/ui
      # See https://stackoverflow.com/a/32785014 for why this is needed.
      - /ui/node_modules
  api:
    build:
      context: api
    ports:
      - 8390:8390
    environment:
      - PATH_PREFIX=/api
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    ports:
      - 5601:5601
  # For convenience, load test data into Elasticsearch.
  index_test_data:
    build:
      context: test
