/**
 * Data Explorer Service
 * API Service that reads from Elasticsearch.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The Cohortname model module.
 * @module model/Cohortname
 * @version 0.0.1
 */
export default class Cohortname {
  /**
   * Constructs a new <code>Cohortname</code>.
   * @alias module:model/Cohortname
   * @class
   */

  constructor() {}

  /**
   * Constructs a <code>Cohortname</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Cohortname} obj Optional instance to populate.
   * @return {module:model/Cohortname} The populated <code>Cohortname</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Cohortname();

      if (data.hasOwnProperty("cohortName")) {
        obj["cohortName"] = ApiClient.convertToType(
          data["cohortName"],
          "String"
        );
      }
      if (data.hasOwnProperty("filter")) {
        obj["filter"] = ApiClient.convertToType(data["filter"], ["String"]);
      }
    }
    return obj;
  }

  /**
   * @member {String} cohortName
   */
  cohortName = undefined;
  /**
   * @member {Array.<String>} filter
   */
  filter = undefined;
}
