/**
 * Data Explorer Service
 * API Service that reads from Elasticsearch.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ExportUrlResponse model module.
* @module model/ExportUrlResponse
* @version 0.0.1
*/
export default class ExportUrlResponse {
    /**
    * Constructs a new <code>ExportUrlResponse</code>.
    * Information for sending data to Terra
    * @alias module:model/ExportUrlResponse
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ExportUrlResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ExportUrlResponse} obj Optional instance to populate.
    * @return {module:model/ExportUrlResponse} The populated <code>ExportUrlResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExportUrlResponse();

            
            
            

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('authorization_domain')) {
                obj['authorization_domain'] = ApiClient.convertToType(data['authorization_domain'], 'String');
            }
        }
        return obj;
    }

    /**
    * URL-encoded signed URL of GCS file containing entities to export.
    * @member {String} url
    */
    url = undefined;
    /**
    * Optional FireCloud authorization domain
    * @member {String} authorization_domain
    */
    authorization_domain = undefined;








}


