/**
 * Data Explorer Service
 * API Service that reads from Elasticsearch.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Field from './Field';





/**
* The FieldsResponse model module.
* @module model/FieldsResponse
* @version 0.0.1
*/
export default class FieldsResponse {
    /**
    * Constructs a new <code>FieldsResponse</code>.
    * Dataset fields for field search.
    * @alias module:model/FieldsResponse
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>FieldsResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/FieldsResponse} obj Optional instance to populate.
    * @return {module:model/FieldsResponse} The populated <code>FieldsResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FieldsResponse();

            
            
            

            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], [Field]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/Field>} fields
    */
    fields = undefined;








}


