# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from data_explorer.models.base_model_ import Model
from data_explorer import util


class Cohortname(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, cohort_name=None, filter=None):  # noqa: E501
        """Cohortname - a model defined in Swagger

        :param cohort_name: The cohort_name of this Cohortname.  # noqa: E501
        :type cohort_name: str
        :param filter: The filter of this Cohortname.  # noqa: E501
        :type filter: List[str]
        """
        self.swagger_types = {'cohort_name': str, 'filter': List[str]}

        self.attribute_map = {'cohort_name': 'cohortName', 'filter': 'filter'}

        self._cohort_name = cohort_name
        self._filter = filter

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The cohortname of this Cohortname.  # noqa: E501
        :rtype: Cohortname
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cohort_name(self):
        """Gets the cohort_name of this Cohortname.


        :return: The cohort_name of this Cohortname.
        :rtype: str
        """
        return self._cohort_name

    @cohort_name.setter
    def cohort_name(self, cohort_name):
        """Sets the cohort_name of this Cohortname.


        :param cohort_name: The cohort_name of this Cohortname.
        :type cohort_name: str
        """

        self._cohort_name = cohort_name

    @property
    def filter(self):
        """Gets the filter of this Cohortname.


        :return: The filter of this Cohortname.
        :rtype: List[str]
        """
        return self._filter

    @filter.setter
    def filter(self, filter):
        """Sets the filter of this Cohortname.


        :param filter: The filter of this Cohortname.
        :type filter: List[str]
        """

        self._filter = filter
