# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from data_explorer.models.base_model_ import Model
from data_explorer import util


class Cohortname(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, cohortname=None, filter=None):  # noqa: E501
        """Cohortname - a model defined in Swagger

        :param cohortname: The cohortname of this Cohortname.  # noqa: E501
        :type cohortname: str
        :param filter: The filter of this Cohortname.  # noqa: E501
        :type filter: List[str]
        """
        self.swagger_types = {
            'cohortname': str,
            'filter': List[str]
        }

        self.attribute_map = {
            'cohortname': 'cohortname',
            'filter': 'filter'
        }

        self._cohortname = cohortname
        self._filter = filter

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The cohortname of this Cohortname.  # noqa: E501
        :rtype: Cohortname
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cohortname(self):
        """Gets the cohortname of this Cohortname.


        :return: The cohortname of this Cohortname.
        :rtype: str
        """
        return self._cohortname

    @cohortname.setter
    def cohortname(self, cohortname):
        """Sets the cohortname of this Cohortname.


        :param cohortname: The cohortname of this Cohortname.
        :type cohortname: str
        """

        self._cohortname = cohortname

    @property
    def filter(self):
        """Gets the filter of this Cohortname.


        :return: The filter of this Cohortname.
        :rtype: List[str]
        """
        return self._filter

    @filter.setter
    def filter(self, filter):
        """Sets the filter of this Cohortname.


        :param filter: The filter of this Cohortname.
        :type filter: List[str]
        """

        self._filter = filter
