# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from data_explorer.models.base_model_ import Model
from data_explorer import util


class ExportUrlResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, url=None):  # noqa: E501
        """ExportUrlResponse - a model defined in Swagger

        :param url: The url of this ExportUrlResponse.  # noqa: E501
        :type url: str
        """
        self.swagger_types = {'url': str}

        self.attribute_map = {'url': 'url'}

        self._url = url

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExportUrlResponse of this ExportUrlResponse.  # noqa: E501
        :rtype: ExportUrlResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self):
        """Gets the url of this ExportUrlResponse.


        :return: The url of this ExportUrlResponse.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this ExportUrlResponse.


        :param url: The url of this ExportUrlResponse.
        :type url: str
        """

        self._url = url
