# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class FacetValue(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, count=None):
        """
        FacetValue - a model defined in Swagger

        :param name: The name of this FacetValue.
        :type name: str
        :param count: The count of this FacetValue.
        :type count: int
        """
        self.swagger_types = {
            'name': str,
            'count': int
        }

        self.attribute_map = {
            'name': 'name',
            'count': 'count'
        }

        self._name = name
        self._count = count

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FacetValue of this FacetValue.
        :rtype: FacetValue
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self):
        """
        Gets the name of this FacetValue.
        Facet value name, for example, \"Male\".

        :return: The name of this FacetValue.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this FacetValue.
        Facet value name, for example, \"Male\".

        :param name: The name of this FacetValue.
        :type name: str
        """

        self._name = name

    @property
    def count(self):
        """
        Gets the count of this FacetValue.
        Facet value count.

        :return: The count of this FacetValue.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """
        Sets the count of this FacetValue.
        Facet value count.

        :param count: The count of this FacetValue.
        :type count: int
        """

        self._count = count

