# coding: utf-8

from __future__ import absolute_import
from data_explorer.models.facet_value import FacetValue
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Facet(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, facet_name=None, values=None):
        """
        Facet - a model defined in Swagger

        :param facet_name: The facet_name of this Facet.
        :type facet_name: str
        :param values: The values of this Facet.
        :type values: List[FacetValue]
        """
        self.swagger_types = {
            'facet_name': str,
            'values': List[FacetValue]
        }

        self.attribute_map = {
            'facet_name': 'facet_name',
            'values': 'values'
        }

        self._facet_name = facet_name
        self._values = values

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Facet of this Facet.
        :rtype: Facet
        """
        return deserialize_model(dikt, cls)

    @property
    def facet_name(self):
        """
        Gets the facet_name of this Facet.

        :return: The facet_name of this Facet.
        :rtype: str
        """
        return self._facet_name

    @facet_name.setter
    def facet_name(self, facet_name):
        """
        Sets the facet_name of this Facet.

        :param facet_name: The facet_name of this Facet.
        :type facet_name: str
        """

        self._facet_name = facet_name

    @property
    def values(self):
        """
        Gets the values of this Facet.

        :return: The values of this Facet.
        :rtype: List[FacetValue]
        """
        return self._values

    @values.setter
    def values(self, values):
        """
        Sets the values of this Facet.

        :param values: The values of this Facet.
        :type values: List[FacetValue]
        """

        self._values = values

