# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from data_explorer.models.base_model_ import Model
from data_explorer.models.facet import Facet  # noqa: F401,E501
from data_explorer import util


class FacetsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, facets=None, count=None):  # noqa: E501
        """FacetsResponse - a model defined in Swagger

        :param facets: The facets of this FacetsResponse.  # noqa: E501
        :type facets: List[Facet]
        :param count: The count of this FacetsResponse.  # noqa: E501
        :type count: int
        """
        self.swagger_types = {'facets': List[Facet], 'count': int}

        self.attribute_map = {'facets': 'facets', 'count': 'count'}

        self._facets = facets
        self._count = count

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FacetsResponse of this FacetsResponse.  # noqa: E501
        :rtype: FacetsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def facets(self):
        """Gets the facets of this FacetsResponse.


        :return: The facets of this FacetsResponse.
        :rtype: List[Facet]
        """
        return self._facets

    @facets.setter
    def facets(self, facets):
        """Sets the facets of this FacetsResponse.


        :param facets: The facets of this FacetsResponse.
        :type facets: List[Facet]
        """

        self._facets = facets

    @property
    def count(self):
        """Gets the count of this FacetsResponse.

        Number of entities represented by current facet selection. For example, this could be 40, representing 40 people.   # noqa: E501

        :return: The count of this FacetsResponse.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this FacetsResponse.

        Number of entities represented by current facet selection. For example, this could be 40, representing 40 people.   # noqa: E501

        :param count: The count of this FacetsResponse.
        :type count: int
        """

        self._count = count
