# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from data_explorer.models.base_model_ import Model
from data_explorer.models.field import Field  # noqa: F401,E501
from data_explorer import util


class FieldsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, fields=None):  # noqa: E501
        """FieldsResponse - a model defined in Swagger

        :param fields: The fields of this FieldsResponse.  # noqa: E501
        :type fields: List[Field]
        """
        self.swagger_types = {
            'fields': List[Field]
        }

        self.attribute_map = {
            'fields': 'fields'
        }

        self._fields = fields

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FieldsResponse of this FieldsResponse.  # noqa: E501
        :rtype: FieldsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def fields(self):
        """Gets the fields of this FieldsResponse.


        :return: The fields of this FieldsResponse.
        :rtype: List[Field]
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this FieldsResponse.


        :param fields: The fields of this FieldsResponse.
        :type fields: List[Field]
        """

        self._fields = fields
