# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from data_explorer.models.base_model_ import Model
from data_explorer.models.search_result import SearchResult  # noqa: F401,E501
from data_explorer import util


class SearchResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, fields=None):  # noqa: E501
        """SearchResponse - a model defined in Swagger

        :param fields: The fields of this SearchResponse.  # noqa: E501
        :type fields: List[SearchResult]
        """
        self.swagger_types = {'fields': List[SearchResult]}

        self.attribute_map = {'fields': 'fields'}

        self._fields = fields

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SearchResponse of this SearchResponse.  # noqa: E501
        :rtype: SearchResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def fields(self):
        """Gets the fields of this SearchResponse.


        :return: The fields of this SearchResponse.
        :rtype: List[SearchResult]
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this SearchResponse.


        :param fields: The fields of this SearchResponse.
        :type fields: List[SearchResult]
        """

        self._fields = fields
