# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from data_explorer.models.base_model_ import Model
from data_explorer.models.search_result import SearchResult  # noqa: F401,E501
from data_explorer import util


class SearchResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, search_results=None):  # noqa: E501
        """SearchResponse - a model defined in Swagger

        :param search_results: The search_results of this SearchResponse.  # noqa: E501
        :type search_results: List[SearchResult]
        """
        self.swagger_types = {'search_results': List[SearchResult]}

        self.attribute_map = {'search_results': 'search_results'}

        self._search_results = search_results

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SearchResponse of this SearchResponse.  # noqa: E501
        :rtype: SearchResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def search_results(self):
        """Gets the search_results of this SearchResponse.


        :return: The search_results of this SearchResponse.
        :rtype: List[SearchResult]
        """
        return self._search_results

    @search_results.setter
    def search_results(self, search_results):
        """Sets the search_results of this SearchResponse.


        :param search_results: The search_results of this SearchResponse.
        :type search_results: List[SearchResult]
        """

        self._search_results = search_results
