#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

./.git/hooks/apply-git-secrets.sh

git secrets --pre_commit_hook -- "$@"

CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`
if [ "$CURRENT_BRANCH" = "master" ]
then
  echo Current branch is master, aborting commit.
  echo Please commit to a working branch and push it to GitHub for review/merge.
  exit 1
fi

readonly changed_files_command="git diff --cached --name-only | grep '\.py$' | grep -v 'servers/[^\/]*/jobs/models' | grep -v 'setup.py'"
readonly files_in_commit=$(eval $changed_files_command)
if [ -n "$files_in_commit" ]; then
  echo "Running yapf linter for python files..."
  # Stash un-staged changes to ensure that the staged changes pass the linter
  git stash -q --keep-index
  readonly yapf_out=$(yapf -d $files_in_commit)
  # Pop the un-staged changes once the lint is complete
  git stash pop -q

  if [ -z "$yapf_out" ]; then
    echo "Passed yapf linter!"
  else
    # Run the linter
    yapf -ir $files_in_commit --exclude ui/node_modules/
  fi
fi
