FROM node

WORKDIR /ui
COPY package.json package-lock.json /ui/
# src/api contains Swagger-generated data_explorer_service. This is needed by
# "npm install" because package.json has a local dependency on
# data_explorer_service.
COPY src/api /ui/src/api
RUN npm install
RUN npm install react-scripts@1.1.1 -g

CMD ["npm", "start"]
