---
swagger: "2.0"
info:
  description: "API Service that reads from Elasticsearch."
  version: "0.0.1"
  title: "Data Explorer Service"
  license:
    name: "BSD"
    url: "http://opensource.org/licenses/BSD-3-Clause"
paths:
  /facets:
    get:
      tags:
      - "Facets"
      description: "Returns facets."
      operationId: "facets_get"
      parameters: []
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/FacetsResponse"
      x-swagger-router-controller: "data_explorer.controllers.facets_controller"
definitions:
  FacetsResponse:
    type: "array"
    description: "Results from a faceted search."
    items:
      $ref: "#/definitions/Facet"
  Facet:
    properties:
      facet_name:
        type: "string"
      values:
        type: "array"
        items:
          $ref: "#/definitions/FacetValue"
    description: "A facet. For example, the Gender facet would include the facet name\
      \ \"Gender\", as well as counts for all possible values.\n"
  FacetValue:
    properties:
      value_name:
        type: "string"
        description: "Facet value name, for example, \"Male\"."
      count:
        type: "integer"
        description: "Facet value count."
    description: "A facet value, for example, \"Male\"/34 hits."
