---
swagger: "2.0"
info:
  description: "API Service that reads from Elasticsearch."
  version: "0.0.1"
  title: "Data Explorer Service"
  license:
    name: "BSD"
    url: "http://opensource.org/licenses/BSD-3-Clause"
paths:
  /facets:
    get:
      tags:
      - "Facets"
      description: "Returns facets."
      operationId: "facets_get"
      parameters:
      - name: "filter"
        in: "query"
        description: "filter represents selected facet values. Elasticsearch query\
          \ will be run only over selected facet values. filter is an array of strings,\
          \ where each string has the format \"facetName=facetValues\". Example url\
          \ /facets?filter=Gender=female,Region=northwest,Region=southwest\n"
        required: false
        type: "array"
        items:
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/FacetsResponse"
      x-swagger-router-controller: "data_explorer.controllers.facets_controller"
definitions:
  FacetsResponse:
    properties:
      facets:
        type: "array"
        items:
          $ref: "#/definitions/Facet"
      count:
        type: "integer"
        description: "Number of entities represented by current facet selection. For\
          \ example, this could be 40, representing 40 people.\n"
    description: "Results from a faceted search."
    example:
      count: 6
      facets:
      - values:
        - name: "name"
          count: 0
        - name: "name"
          count: 0
        name: "name"
      - values:
        - name: "name"
          count: 0
        - name: "name"
          count: 0
        name: "name"
  Facet:
    properties:
      name:
        type: "string"
        description: "Facet name, for example, \"Gender\"."
      values:
        type: "array"
        items:
          $ref: "#/definitions/FacetValue"
    description: "A facet. For example, the Gender facet would include the facet name\
      \ \"Gender\", as well as counts for all possible values.\n"
    example:
      values:
      - name: "name"
        count: 0
      - name: "name"
        count: 0
      name: "name"
  FacetValue:
    properties:
      name:
        type: "string"
        description: "Facet value name, for example, \"Male\"."
      count:
        type: "integer"
        description: "Facet value count."
    description: "A facet value, for example, \"Male\"/34."
    example:
      name: "name"
      count: 0
