---
swagger: "2.0"
info:
  description: "API Service that reads from Elasticsearch."
  version: "0.0.1"
  title: "Data Explorer Service"
  license:
    name: "BSD"
    url: "http://opensource.org/licenses/BSD-3-Clause"
paths:
  /dataset:
    get:
      tags:
      - "Dataset"
      description: "Gets dataset information, such as name."
      operationId: "dataset_get"
      parameters: []
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/DatasetResponse"
      x-swagger-router-controller: "data_explorer.controllers.dataset_controller"
  /facets:
    get:
      tags:
      - "Facets"
      description: "Returns facets."
      operationId: "facets_get"
      parameters:
      - name: "filter"
        in: "query"
        description: "filter represents selected facet values. Elasticsearch query\
          \ will be run only over selected facet values. filter is an array of strings,\
          \ where each string has the format \"facetName=facetValue\". Example url\
          \ /facets?filter=Gender=female,Region=northwest,Region=southwest\n"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "pipes"
      - name: "extraFacets"
        in: "query"
        description: "extraFacets represents the fields selected from the field search\
          \ box. extraFacets is a list of Elasticsearch field names. In the returned\
          \ list of facets, the extra facets will come before the facets from ui.json."
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "pipes"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/FacetsResponse"
      x-swagger-router-controller: "data_explorer.controllers.facets_controller"
  /fields:
    get:
      tags:
      - "Fields"
      description: "Returns dataset fields for field search."
      operationId: "fields_get"
      parameters: []
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/FieldsResponse"
      x-swagger-router-controller: "data_explorer.controllers.fields_controller"
  /exportUrl:
    post:
      tags:
      - "ExportUrl"
      description: "Creates and returns a signed URL to a GCS zip file of JSON files.\
        \ The JSON files represent entities to be exported to a Saturn workspace.\
        \ https://bvdp-saturn-prod.appspot.com/#import-data may be called with the\
        \ url parameter set to this url. For each JSON file, https://rawls.dsde-prod.broadinstitute.org/#!/entities/create_entity\
        \ may be called with the JSON as the POST body.\n"
      operationId: "export_url_post"
      parameters:
      - in: "body"
        name: "exportUrlRequest"
        required: false
        schema:
          $ref: "#/definitions/exportUrlRequest"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/ExportUrlResponse"
      x-swagger-router-controller: "data_explorer.controllers.export_url_controller"
definitions:
  DatasetResponse:
    properties:
      name:
        type: "string"
      enableFieldSearch:
        type: "boolean"
    description: "Dataset information."
    example:
      enableFieldSearch: true
      name: "name"
  FacetsResponse:
    properties:
      facets:
        type: "array"
        items:
          $ref: "#/definitions/Facet"
      count:
        type: "integer"
        description: "Number of entities represented by current facet selection. For\
          \ example, this could be 40, representing 40 people.\n"
    description: "Results from a faceted search."
    example:
      count: 6
      facets:
      - values:
        - name: "name"
          count: 0
        - name: "name"
          count: 0
        name: "name"
        description: "description"
      - values:
        - name: "name"
          count: 0
        - name: "name"
          count: 0
        name: "name"
        description: "description"
  Facet:
    properties:
      name:
        type: "string"
        description: "Facet name, for example, \"Gender\"."
      description:
        type: "string"
        description: "Optional facet description."
      values:
        type: "array"
        items:
          $ref: "#/definitions/FacetValue"
    description: "A facet. For example, the Gender facet would include the facet name\
      \ \"Gender\", as well as counts for all possible values.\n"
    example:
      values:
      - name: "name"
        count: 0
      - name: "name"
        count: 0
      name: "name"
      description: "description"
  FacetValue:
    properties:
      name:
        type: "string"
        description: "Facet value name, for example, \"Male\"."
      count:
        type: "integer"
        description: "Facet value count."
    description: "A facet value, for example, \"Male\"/34."
    example:
      name: "name"
      count: 0
  ExportUrlResponse:
    properties:
      url:
        type: "string"
        description: "URL-encoded signed URL of GCS file containing entities to export."
      authorization_domain:
        type: "string"
        description: "Optional FireCloud authorization domain"
    description: "Information for sending data to Saturn"
    example:
      authorization_domain: "authorization_domain"
      url: "url"
  FieldsResponse:
    properties:
      fields:
        type: "array"
        items:
          $ref: "#/definitions/Field"
    description: "Dataset fields for field search."
    example:
      fields:
      - name: "name"
        description: "description"
        elasticsearch_name: "elasticsearch_name"
      - name: "name"
        description: "description"
        elasticsearch_name: "elasticsearch_name"
  Field:
    properties:
      name:
        type: "string"
        description: "Field name, for example, \"Gender\"."
      description:
        type: "string"
        description: "Optional field description."
      elasticsearch_name:
        type: "string"
        description: "The Elasticsearch field name."
    description: "A field. For example, a BigQuery Gender column could include the\
      \ field name \"Gender\", description \"Sex at birth\" and elasticsearch field\
      \ name \"project_id.dataset_id.table_name.Gender\".\n"
    example:
      name: "name"
      description: "description"
      elasticsearch_name: "elasticsearch_name"
  exportUrlRequest:
    type: "object"
    properties:
      cohortName:
        type: "string"
      filter:
        type: "array"
        items:
          type: "string"
