swagger: "2.0"
info:
  title: Data Explorer Service
  description: API Service that reads from Elasticsearch.
  license:
    name: BSD
    url: "http://opensource.org/licenses/BSD-3-Clause"
  version: "0.0.1"
paths:
  /dataset:
    get:
      description: Gets dataset information, such as name.
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/DatasetResponse"
      tags:
        # Put in dataset_controller.py instead of default_controller.py.
        - Dataset
  /facets:
    # Example url /facets?project_id.dataset_id.table_name.filter=Gender=female,project_id.dataset_id.table_name.Region=northwest,project_id.dataset_id.table_name.Region=southwest
    get:
      description: Returns facets.
      parameters:
        - name: filter
          # Unfortunately OpenAPI 2.0 doesn't allow objects in GET query
          # parameters. So hardcode something like "Gender=female".
          # TODO(#32): Investigate switching to OpenAPI 3.0.
          description: >
            filter represents selected facet values. Elasticsearch query will
            be run only over selected facet values. filter is an array of
            strings, where each string has the format "esFieldName=facetValue".
            Example url /facets?filter=Gender=female,Region=northwest,Region=southwest
          in: query
          type: array
          # Default collectionFormat is csv. With csv, faceted search doesn't
          # work when facet value has a comma. So switch to pipes; pipe in facet
          # value is much more rare.
          collectionFormat: pipes
          items:
            type: string
        - name: extraFacets
          description:
            extraFacets represents the fields selected from the field search box.
            extraFacets is a list of Elasticsearch field names. In the returned
            list of facets, the extra facets will come before the facets from ui.json.
          in: query
          collectionFormat: pipes
          type: array
          items:
            type: string
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/FacetsResponse"
      tags:
        # Put in facets_controller.py instead of default_controller.py.
        - Facets
  /search:
    get:
      description: >
        Free text search over dataset. If query is empty, this returns all
        dataset fields, to populate the search drop-down on initial page load.
        If query is set, this returns only dataset fields that match the query.
      parameters:
        - name: query
          description: >
            What was typed into search box. Say user typed "foo". query is "foo";
            Elasticsearch will be searched for "foo*".
          in: query
          type: string
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/SearchResponse"
      tags:
        # Put in search_controller.py instead of default_controller.py.
        - Search
  /exportUrl:
    # This is post because this is not idempotent; a GCS file is created.
    post:
      description: >
        Creates and returns a signed URL to a GCS zip file of JSON files. The
        JSON files represent entities to be exported to a Terra workspace.
        https://app.terra.bio/#import-data may be called with the url parameter
        set to this url. For each JSON file,
        https://rawls.dsde-prod.broadinstitute.org/#!/entities/create_entity
        may be called with the JSON as the POST body.
      parameters:
        - name: "exportUrlRequest"
          in: "body"
          schema:
            type: object
            properties:
              cohortName:
                type: string
              filter:
                type: array
                # Default collectionFormat is csv. With csv, faceted search doesn't
                # work when facet value has a comma. So switch to pipes; pipe in facet
                # value is much more rare.
                collectionFormat: pipes
                items:
                  type: string
              dataExplorerUrl:
                type: string
              sqlQuery:
                type: string
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/ExportUrlResponse"
      tags:
        # Put in export_url_controller.py instead of default_controller.py.
        - ExportUrl
definitions:
  DatasetResponse:
    description: "Dataset information."
    properties:
      name:
        type: string
      search_placeholder_text:
        type: string
        description: Optional. What to show in the search box by default
      time_series_unit:
        type: string
        description: >
          If time_series_column in bigquery.json is set, this must be
          set. This is used to label the time axis -- eg Month or
          Year.
  FacetsResponse:
    description: "Results from a faceted search."
    properties:
      facets:
        type: array
        items:
          $ref: "#/definitions/Facet"
      count:
        type: integer
        description: >
          Number of entities represented by current facet selection. For
          example, this could be 40, representing 40 people.
      invalid_filter_facets:
        description: >
          Facets that were passed in filter param that don't exist in
          Elasticsearch index. Example:
          - Data Explorer url contains
            filter=amppd.2019_v1_0101.demographics.sex=female which is valid. User
            saves a cohort with this filter
          - A new version of AMP PD is released. (Data explorer url remains the
            same.) The dataset 2019_v1_0101 is replaced by dataset 2019_v2_0401.
          - User won't be able to open saved cohort in DE;
            amppd.2019_v1_0101.demographics.sex is no longer is Elasticsearch
            index. invalid_filter_facets will contain
            amppd.2019_v1_0101.demographics.sex
        type: array
        items:
          type: string
      invalid_extra_facets:
        description: >
          Facets that were passed in extraFacets param that don't exist in
          Elasticsearch index. Example:
          - Data Explorer url contains
            extraFacets=amppd.2019_v1_0101.demographics.sex which is valid. User
            saves a cohort with this extra facet
          - A new version of AMP PD is released. (Data explorer url remains the
            same.) The dataset 2019_v1_0101 is replaced by dataset 2019_v2_0401.
          - User won't be able to open saved cohort in DE;
            amppd.2019_v1_0101.demographics.sex is no longer is Elasticsearch
            index. invalid_extra_facets will contain
            amppd.2019_v1_0101.demographics.sex
        type: array
        items:
          type: string
      sql_query:
        type: string
        description: >
          SQL query that can be used in BigQuery to get the cohort 
          (list of participants) of the current filter.
  Facet:
    description: >
      A facet. For example, the Gender facet would include the facet name
      "Gender", as well as counts for all possible values.
    properties:
      name:
        type: string
        description: Facet name, for example, "Gender".
      description:
        type: string
        description: Optional facet description.
      es_field_name:
        type: string
        description: The Elasticsearch field name.
      es_field_type:
        type: string
        description: The Elasticsearch field type.
      # If this is a regular facet (https://i.imgur.com/ug1mSEr.png),
      # only value_names and value_counts are set.  If this is a time
      # series facet (https://i.imgur.com/IU2SqWv.png), then
      # value_names, time_names, time_series_value_counts are
      # set. Consider https://i.imgur.com/IU2SqWv.png: the data is a
      # table with 6 rows and 3 columns. Column names are time_names;
      # row names are value_names; time_series_value_counts are the
      # numbers in the table.
      value_names:
        type: array
        items:
          type: string
        description: >
          Array of names of possible facet values.
      value_counts:
        type: array
        items:
          type: integer
        description: Array of counts for each facet value.
      time_names:
        type: array
        # This is string because time may be "Unknown"
        items:
          type: string
        description: Array of times.
      time_series_value_counts:
        type: array
        items:
          type: array
          items:
            type: integer
        description: >
          2-dimensional array of facet value counts, indexed by time
          then value; indexes correspond to time_names and then
          value_names.
  ExportUrlResponse:
    description: "Information for sending data to Terra"
    properties:
      url:
        type: string
        description: "URL-encoded signed URL of GCS file containing entities to export."
      authorization_domain:
        type: string
        description: "Optional FireCloud authorization domain"
  SearchResponse:
    properties:
      search_results:
        type: array
        items:
          $ref: "#/definitions/SearchResult"
  SearchResult:
    description: >
      Can represent a facet (Gender), or a facet and selected value (Gender = female).
    properties:
      facet_name:
        type: string
        description: The name of the facet.
      facet_description:
        type: string
        description: Optional. The description of the facet.
      elasticsearch_field_name:
        type: string
        description: The Elasticsearch field name.
      facet_value:
        type: string
        description: >
          If this search result represents a facet, facet_value is the empty string.
          If this search result represents a facet and selected value, facet_value is the selected value.
      is_time_series:
        type: boolean
        description: >
          True if this is a time series field at a specific point in time.
