swagger: '2.0'
info:
  title: Data Explorer Service
  description: API Service that reads from Elasticsearch.
  license:
    name: BSD
    url: 'http://opensource.org/licenses/BSD-3-Clause'
  version: '0.0.1'
paths:
  /facets:
    get:
      description: Returns facets.
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/FacetsResponse'
      tags:
        # Put in facets_controller.py instead of default_controller.py.
        - Facets
definitions:
  FacetsResponse:
    description: "Results from a faceted search."
    properties:
      facets:
        type: array
        items:
          $ref: '#/definitions/Facet'
      count:
        type: integer
        description: >
          Number of entities represented by current facet selection. For
          example, this could be 40, representing 40 people.
  Facet:
    description: >
      A facet. For example, the Gender facet would include the facet name
      "Gender", as well as counts for all possible values.
    properties:
      name:
        type: string
        descrption: Facet name, for example, "Gender".
      values:
        type: array
        items:
          $ref: '#/definitions/FacetValue'
  FacetValue:
    description: A facet value, for example, "Male"/34.
    properties:
      name:
        type: string
        description: Facet value name, for example, "Male".
      count:
        type: integer
        description: Facet value count.

