/**
 * Data Explorer Service
 * API Service that reads from Elasticsearch.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", "../../src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require("../../src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DataExplorerService);
  }
})(this, function(expect, DataExplorerService) {
  "use strict";

  var instance;

  beforeEach(function() {
    instance = new DataExplorerService.ExportUrlRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === "function") return object[getter]();
    else return object[property];
  };

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === "function") object[setter](value);
    else object[property] = value;
  };

  describe("ExportUrlRequest", function() {
    it("should create an instance of ExportUrlRequest", function() {
      // uncomment below and update the code to test ExportUrlRequest
      //var instane = new DataExplorerService.ExportUrlRequest();
      //expect(instance).to.be.a(DataExplorerService.ExportUrlRequest);
    });

    it('should have the property cohortName (base name: "cohortName")', function() {
      // uncomment below and update the code to test the property cohortName
      //var instane = new DataExplorerService.ExportUrlRequest();
      //expect(instance).to.be();
    });

    it('should have the property filter (base name: "filter")', function() {
      // uncomment below and update the code to test the property filter
      //var instane = new DataExplorerService.ExportUrlRequest();
      //expect(instance).to.be();
    });
  });
});
